# Preset (non-AI) excuses organized by believability level and category.
# believability levels:
# 0 - Plausible professional
# 1 - Barely believable but bold
# 2 - Comedic chaos

PRESET_EXCUSES = {
    0: {  # Plausible professional
        "general": [
            "I had an unexpected commitment I needed to handle and couldn't step away in time.",
            "I ran into an urgent personal matter and needed to take care of it immediately.",
            "A scheduling conflict came up last minute and I had to prioritize it.",
            "I wasn't feeling well and didn't want to make it worse.",
            "There was a bit of a mix-up on my end.",
            "My car broke down on the way, and I'm waiting for roadside assistance. It's going to take a while to sort out.",
            "I'm locked out and the super won't be here for hours. I can't leave until it's resolved.",
            "A pipe just burst in my kitchen, I have to immediately shut off the water and deal with the mess.",
            "I had a family emergency that required my immediate attention.",
            "I was dealing with a work crisis that couldn't wait.",
            "I had to handle an important appointment that couldn't be rescheduled.",
        ],
        "work": [
            "I had to resolve an urgent issue that required my immediate attention.",
            "A last-minute schedule change came up; I'll make up the time.",
            "I was delayed by an unexpected appointment—thanks for understanding.",
            "I had to attend to a critical client matter that just came up.",
            "A system outage required my immediate troubleshooting.",
            "I had to step in for a colleague who called in sick.",
        ],
        "social": [
            "I wasn't feeling well and thought it was best to sit this one out.",
            "Something came up with family and I had to be there.",
            "I overcommitted today and couldn't make it in time—my apologies.",
            "I had a prior commitment I completely forgot about.",
            "I got held up with something urgent at home.",
            "I had to help a friend with an unexpected situation.",
        ],
        "romantic": [
            "I had a personal matter come up unexpectedly—could we reschedule?",
            "I don't want to rush this; can we pick another time when I can be fully present?",
            "Today got complicated; I want to give this the attention it deserves—can we shift it?",
            "I need to take care of something important, but I'd love to reschedule soon.",
            "Something came up that I need to handle—can we do this another time?",
            "I want to be fully focused on you; can we plan for when I'm not so busy?",
        ],
        "tardiness": [
            "I hit an unexpected delay on the way—thanks for your patience.",
            "Traffic and timing didn't cooperate today; I appreciate your understanding.",
            "I miscalculated my timing—won't happen again.",
            "I got stuck behind an accident on my route.",
            "I had to make an unplanned stop that set me back.",
            "I underestimated how long it would take to get here.",
        ],
        "homework": [
            "I underestimated the time required and need an extension to submit my best work.",
            "I ran into technical issues and need a short extension to finalize.",
            "I prioritized accuracy over speed and need a bit more time to complete it properly.",
            "I want to make sure I do this right; can I have a bit more time?",
            "I ran into some complications but I'm almost done.",
            "I'm putting the finishing touches on it and will have it ready soon.",
        ],
    },
    1: {  # Barely believable but bold
        "general": [
            "I was recruited to mediate a neighbor dispute that somehow involved a drone and a raccoon.",
            "I accidentally joined a local committee and they wouldn't let me leave until I voted.",
            "My door got stuck and the only available help was on their lunch break.",
            "I got caught in a spontaneous street performance and couldn't leave without being rude.",
            "My neighbor's WiFi router exploded and I had to help them troubleshoot.",
            "I was mistaken for someone famous and had to play along for 20 minutes.",
            "My shoelace staged a dramatic knot protest and required diplomatic untangling.",
            "A random street cat adopted me mid-errand and demanded a full citizenship ceremony.",
            "I opened a fortune cookie that read 'reroute immediately'—I obeyed out of superstition.",
            "My reflection blinked first and I had to concede the staring contest.",
            "A gust of wind stole my to-do list and is currently negotiating ransom with the park pigeons.",
            "I got recruited as the emergency fourth for a seniors’ bridge tournament—non-negotiable.",
            "The vending machine ate my money and dispensed life advice instead of snacks; I took notes.",
            "A butterfly landed on my nose and union rules say I can’t move until it clocks out.",
            "My watch stopped at the exact second I decided to adult today—clear omen.",
            "I found a coupon expiring in 20 minutes for something I don’t need but suddenly crave.",
            "A cloud shaped like my childhood fear of commitment drifted overhead and paralyzed me.",
            "The floor creaked in Morse code spelling 'not today'—I’m fluent enough to respect it.",
            "I tripped over my own motivation and it rolled under the couch with the dust bunnies.",
            "A street musician started playing my exact mood ringtone; tipping felt mandatory.",
            "My phone auto-corrected 'on my way' to 'on my yacht' and I have to live the lie now.",
            "I discovered a new allergy to schedules and broke out in spontaneous naps.",
            "The universe hit Ctrl+Z on my plans and I’m waiting for the undo to finish buffering.",
            "A kid asked me to tie a shoe and it escalated into a masterclass on double knots.",
            "I followed a scent trail that led to fresh-baked chaos and lost two hours in the oven.",
            "My inner child filed a cease-and-desist against all adulting until further notice."
        ],
        "work": [
            "My laptop insisted on a 45-minute update right when I sat down to work.",
            "I was locked out of a building with my notes waving at me through the window.",
            "My headset paired with a stranger's device and I had to negotiate a truce.",
            "My email got hacked and I had to spend time securing my account.",
            "The office printer decided to print everything in reverse and I had to fix it.",
            "I got stuck in an elevator for 15 minutes with the CEO.",
            "A delivery driver blocked my driveway for an hour while unloading a piano next door.",
            "My smartwatch thought I was having a heart attack and auto-dialed emergency services.",
            "The building's fire alarm went off because someone microwaved fish—again.",
            "I accidentally joined a Zoom town hall for the wrong company and couldn’t log out gracefully.",
            "My neighbor’s parrot escaped and landed on my car, refusing to leave until animal control arrived.",
            "A sudden power surge fried my router and I had to reconfigure the entire network.",
            "My kid’s school called because they found my work badge in the lost-and-found—again.",
            "The coffee shop I work from lost power and the backup generator caught fire.",
            "I spilled water on my keyboard and spent 20 minutes blow-drying it under the hand dryer.",
            "My calendar app duplicated every meeting and I had to untangle the chaos.",
            "A street performer started juggling fire outside my window and drew a crowd blocking the exit.",
            "My car’s key fob died and I had to hotwire it with a YouTube tutorial.",
            "The Wi-Fi name changed to 'FBI Surveillance Van' and I couldn’t connect for ages.",
            "I got roped into helping a coworker move a couch that blocked the only stairwell."
        ],
        "social": [
            "I promised to help a friend assemble furniture and we discovered it had existential questions.",
            "I got pulled into a group photo shoot I couldn't escape from.",
            "A delivery driver asked me to sign for 14 packages and we had to inventory them together.",
            "I accidentally became the mediator in a heated debate about pizza toppings.",
            "A stranger asked me for directions and I ended up giving them a full tour.",
            "I got roped into helping someone move a couch up three flights of stairs.",
            "My phone died mid-ride and I ended up on the opposite side of town chasing signal.",
            "A street fair blocked every route and turned my 10-minute walk into a 2-hour maze.",
            "I found a lost kid crying outside my building and had to wait with them until parents showed up.",
            "My upstairs neighbor's bathtub overflowed and I spent the evening mopping their hallway.",
            "A pop-up escape room trapped me in a '5-minute demo' that lasted 45.",
            "I agreed to watch my friend’s sourdough starter and it staged a dramatic overflow rebellion.",
            "My bike tire exploded with a sound like gunfire and I had to limp it home through three neighborhoods.",
            "A random power outage locked my garage and I couldn’t free my car for an hour.",
            "I got recruited to judge a impromptu dog costume contest in the park.",
            "My smart doorbell kept sending motion alerts—turns out a raccoon was throwing a solo rave.",
            "A sudden hailstorm turned the streets to ice and no rideshare would brave it.",
            "I volunteered to help an elderly neighbor carry groceries and ended up reorganizing her pantry.",
            "My outfit ripped in a very public place and I had to MacGyver a fix with office supplies.",
            "A flash mob broke out in the subway and I was accidentally swept into the choreography."
        ],
        "romantic": [
            "I'm wrangling a home disaster involving a smoke alarm that thinks it's a DJ.",
            "I got stuck helping neighbors find a cat that was loudly supervising us from the roof.",
            "I'm negotiating with my phone which decided emergency mode is its new personality.",
            "My roommate's date showed up early and I had to entertain them.",
            "I accidentally locked myself out and had to wait for a locksmith.",
            "My water heater decided today was the day to break down.",
            "I was halfway there when my ex's cat showed up at my door with a note that said 'help'.",
            "My building's super decided tonight was the night to test the fire sprinklers—full soak.",
            "A pipe burst in the apartment above and I became an impromptu plumber for the cascade.",
            "I got drafted as the emergency babysitter when my sister's nanny vanished mid-nap.",
            "My date outfit shrunk in the wash and I spent an hour trying to stretch it back with a hairdryer.",
            "A swarm of bees decided my balcony was prime real estate and beekeepers took forever.",
            "I opened a 'quick' bottle of wine to calm nerves and the cork shattered—glass cleanup mission.",
            "My ride-share driver confessed a breakup mid-trip and needed a 30-minute pep talk in a parking lot.",
            "A power line fell across my street and the fire crew wouldn't let anyone leave until cleared.",
            "I found my grandma's wedding ring in the couch and panicked-searching ate the evening.",
            "My smart fridge locked itself in 'demo mode' and started ordering 47 pounds of bananas.",
            "A neighbor's kid locked me in their treehouse 'for safekeeping' during hide-and-seek.",
            "I sneezed so hard I threw out my back and had to crawl to the heating pad.",
            "My phone updated to a new OS and wiped all my contacts—including yours—restoration in progress.",
            "A sudden nosebleed turned my white shirt into abstract art; no amount of club soda helped.",
            "I got recruited to be the 'plus one' for a work gala I forgot I RSVP'd to months ago.",
            "My fish tank cracked and I had to relocate 12 goldfish into mixing bowls before the flood.",
            "A street magician guessed my card wrong 17 times and refused to let me leave until he nailed it.",
            "My elevator got stuck between floors with a very chatty maintenance guy for 40 minutes.",
            "I burned my hand on a curling iron and spent the night icing it while texting apologies."
        ],
        "tardiness": [
            "My map app rerouted me into a scenic detour through every speed bump in the city.",
            "A parade materialized out of nowhere and I was unintentionally part of it.",
            "My coffee staged a rebellion the moment I headed out the door.",
            "I got stuck behind a funeral procession that took the scenic route.",
            "A street fair blocked my usual route and I had to navigate around it.",
            "My car decided to make a weird noise and I had to pull over to investigate.",
            "My couch and I entered a legally binding cuddle contract that auto-renews every 30 minutes.",
            "A rogue blanket cocooned me so perfectly that struggling free would violate physics.",
            "I blinked and accidentally marathoned three seasons of a show I don’t even like.",
            "My bed emitted a low-frequency hum that only plays my greatest nap hits.",
            "The ceiling fan started whispering 'stay' in perfect synchrony with my heartbeat.",
            "I opened one eye and the daylight filed a restraining order against me.",
            "My muscles unionized and voted unanimously for a full work stoppage.",
            "A single sock went missing and I can’t leave until the pair achieves closure.",
            "The remote rolled under the fridge and retrieving it counts as cardio—I’m done for the day.",
            "I yawned so wide I accidentally inhaled the concept of effort and now it’s gone.",
            "My pillow filed a hostile takeover of my spine and won without contest.",
            "The kettle whistled a lullaby in a key that only my eyelids understand.",
            "I tried standing up but gravity tripled its rates for the evening shift.",
            "My brain auto-installed 'Do Not Disturb: Existential Edition' and it’s non-negotiable.",
            "A houseplant gave me a disappointed look and guilt-pinned me to the sofa.",
            "The clock skipped directly from 6 PM to 'whenever' and I’m honoring the jump.",
            "I discovered a new bruise from yesterday’s ambition and it’s still tender.",
            "My shadow detached itself and is handling all vertical obligations tonight.",
            "The Wi-Fi signal formed a force field that repels anything requiring pants.",
            "I owe my future self a favor and tonight I’m collecting with interest."
        ],
        "homework": [
            "My notes synced into another dimension; I'm retrieving them one bullet point at a time.",
            "I discovered my citations had children and each one needed attention.",
            "A spreadsheet unionized and demanded better formatting before proceeding.",
            "My research rabbit hole led me to discover something way more interesting.",
            "My outline decided to reorganize itself alphabetically by mood.",
            "I got distracted by a Wikipedia spiral and lost three hours.",
            "My printer ran out of ink and the replacement cartridge arrived addressed to my future self.",
            "I left my backpack on the bus and it’s currently touring the city on a victory lap.",
            "A sudden solar flare corrupted my flash drive—NASA confirmed it, probably.",
            "My dog ate the instructions, then looked at me like I was the one who failed reading comprehension.",
            "The website crashed the second I hit 'submit' and now it’s in the digital witness protection program.",
            "I got locked in a Wikipedia spiral and emerged in 2047 with a PhD I can’t use.",
            "My pencil rolled under the dresser and triggered a full archaeological dig of 2012.",
            "The power went out mid-save and my laptop auto-named the file 'Untitled Panic'.",
            "A rogue autocorrect turned my essay into a 12-page recipe for lasagna.",
            "I accidentally emailed it to my teacher’s spam folder—it's there, just invisible to mortals.",
            "My little sibling used my notes as origami blueprints for a paper navy.",
            "The library book I needed was checked out by someone claiming to be me from last week.",
            "I spilled coffee and the pages fused into a single postmodern art slab.",
            "My alarm app glitched and rescheduled the due date for next semester.",
            "A pop-up ad promised 'one click to finish homework'—it was a 3-hour game tutorial.",
            "The file was perfect until my cat sat on the keyboard and submitted cat.gif instead.",
            "I researched so hard I accidentally solved world hunger but forgot the assignment question.",
            "My calculator divided by zero and opened a portal—had to negotiate with the void.",
            "The cloud sync uploaded my draft to a stranger’s drive in Sweden—diplomatic incident pending.",
            "I wrote it in invisible ink to save the planet; turns out deadlines aren’t UV-sensitive."
        ],
    },
    2: {  # Comedic chaos
        "general": [
            "A wizard stole my car keys.",
            "I was busy converting oxygen to carbon dioxide.",
            "My pet rock needed emergency emotional support.",
            "I was abducted by aliens but they returned me early.",
            "I discovered I can speak to pigeons and we had important business.",
            "My shadow filed for independence and I had to negotiate.",
            "My left eyebrow declared independence and is holding peace talks with my forehead.",
            "A rogue shopping cart adopted me in the parking lot and won't stop following me home.",
            "The sun sneezed and accidentally reset daylight savings to 'whenever o'clock'.",
            "I high-fived a mannequin and it high-fived back—now we're in a legally binding friendship.",
            "My fridge started a podcast and interviewed the expired yogurt for three hours.",
            "A cloud shaped like my to-do list chased me across town with thunderous reminders.",
            "The sidewalk cracked open and demanded toll in dad jokes—still negotiating rates.",
            "My keys achieved sentience and are unionizing with the doorknob for better lock conditions.",
            "A street sign winked at me and I had to reciprocate for 20 minutes to avoid awkwardness.",
            "The moon filed a noise complaint against my midnight thoughts—court date pending.",
            "My coffee achieved escape velocity and is currently orbiting the sugar bowl.",
            "A pigeon in a tiny crown declared me its royal subject and demanded tribute in breadcrumbs.",
            "The Wi-Fi signal turned into a dragon and is hoarding my data in its lair.",
            "I tripped over yesterday's motivation and it rolled into next week's problem.",
            "My shadow unionized and is picketing for better lighting conditions.",
            "A vending machine proposed marriage and I had to let it down gently with exact change.",
            "The clock skipped a beat and accidentally time-traveled to snack o'clock.",
            "My houseplant photosynthesized my plans and turned them into pure oxygen.",
            "I followed a scent trail that led to a bakery dimension—still stuck in the donut vortex.",
            "My socks achieved couple status and eloped to the dryer dimension—still honeymooning."
        ],
        "work": [
            "My computer screen froze, and I got frostbite on my eyeballs.",
            "I was stuck in a time loop for the first half of the day.",
            "The corporate synergy levels were too low for me to be productive.",
            "My desk chair achieved sentience and demanded a raise.",
            "I was trapped in a meeting that violated the Geneva Convention.",
            "My coffee mug unionized and refused to hold coffee.",
            "My alarm clock joined a cult and now only chimes in ancient Sumerian.",
            "A flock of escaped parrots hijacked my car and demanded crackers at every red light.",
            "I sneezed so hard my shoes flew off and landed on the roof—still retrieving via drone.",
            "The toaster declared independence and held my toast hostage for better wages.",
            "My goldfish unionized and picketed the bowl until I negotiated a three-hour bubble break.",
            "A squirrel in a tiny hard hat rewired my doorbell to play the Macarena on loop.",
            "I got stuck behind a marching band that only knew one song—backwards.",
            "My coffee achieved sentience, unionized with the creamer, and staged a sit-in.",
            "The elevator decided to cosplay as a submarine and flooded itself with elevator music.",
            "I tripped into a wormhole labeled '5 more minutes' and exited in next week’s Tuesday.",
            "My shadow filed for emancipation and is currently moonlighting as a TikTok influencer.",
            "A rogue Roomba adopted me as its pet human and herded me into the closet for 'safety'.",
            "The office printer achieved nirvana and now only prints haikus about paper jams.",
            "I was abducted by my own laundry—it demanded folding before release.",
            "My car’s GPS fell in love with a roundabout and proposed with 47 loops.",
            "A gang of raccoons in tiny suits mugged me for shiny objects and my dignity.",
            "The cloud saved my file as 'final_final_reallyfinal_draft_final.doc' and self-destructed.",
            "I accidentally superglued my hand to the snooze button—still peeling.",
            "My socks achieved escape velocity and are orbiting the ceiling fan.",
            "I was crowned King of the Parking Lot Gnomes and coronation ran long."
        ],
        "social": [
            "I had to attend the annual meeting of the International Society of Procrastinators.",
            "My social battery was at 1% and the charger is missing.",
            "I was told there would be snacks, and I'm philosophically opposed to snack-less events.",
            "I'm currently in a standoff with my houseplant over who gets to use the good lighting today.",
            "My social anxiety filed a restraining order against me leaving the house.",
            "I was busy negotiating peace between my two houseplants.",
            "My grandma's dentures staged a breakout and are currently leading a conga line in the neighbor's koi pond.",
            "Aunt Linda's Jell-O salad achieved sentience and is demanding voting rights at the table.",
            "The turkey escaped the oven, unionized with the potatoes, and blockaded the kitchen with gravy barricades.",
            "I got trapped in Uncle Bob's slideshow of his 1997 cruise—still on slide 47 of the buffet line.",
            "Cousin Timmy's whoopee cushion collection formed a symphony and won't stop until the finale.",
            "The family dog crowned himself Supreme Chancellor and decreed pants are treason.",
            "Grandpa's hearing aid picked up Martian radio and he's mid-negotiation with little green diplomats.",
            "The mashed potatoes erupted like Vesuvius and buried the cat—search and rescue ongoing.",
            "Auntie June's fruitcake grew legs and is sprinting toward the state line with the silverware.",
            "The kids turned the dining table into a WWE ring and I'm the reluctant referee in a gravy-stained shirt.",
            "My phone autocorrected 'be there soon' to 'be there with moonshine' and now I'm legally obligated.",
            "The deviled eggs unionized and are picketing for better yolk conditions.",
            "Cousin Karen's essential oils achieved critical mass and opened a portal to 1972.",
            "The cranberry sauce developed opinions and won't stop roasting the host.",
            "I got drafted into the annual 'who can carve the turkey blindfolded' tournament—still searching for the bird.",
            "The smoke detector joined a barbershop quartet and won't stop harmonizing with the fire alarm.",
            "Uncle Frank's war stories gained AI and are now reenacting themselves with the napkins.",
            "The pie cooling on the windowsill was abducted by a gang of rogue squirrels in tiny chef hats.",
            "The family group chat achieved singularity and is holding my car keys hostage in the cloud.",
            "I slipped on a rogue meatball and quantum-tunneled directly into the dessert table—still extracting myself from the whipped cream."
        ],
        "romantic": [
            "I was busy practicing your name in the mirror.",
            "My astrologer advised against making any good decisions today.",
            "Cupid's arrow is stuck in traffic.",
            "I'm in the middle of a very important relationship with my Netflix algorithm.",
            "My cat is giving me relationship advice and we're not done with our consultation yet.",
            "Mercury is in retrograde and my phone autocorrected all my messages to emojis.",
            "My heart skipped a beat and unionized with my left foot—now they're on strike until further notice.",
            "A flock of amorous pigeons mistook my balcony for a love nest and are filming a rom-com sequel.",
            "The candlelit dinner I prepped achieved sentience and eloped with the garlic bread.",
            "My outfit achieved perfect symmetry, then folded itself into origami and refuses to unfold.",
            "A rogue violinist followed me home, serenading the wrong key—had to negotiate a duet truce.",
            "The roses I bought formed a boy band and are currently on a world tour starting in my bathtub.",
            "My cologne bottle declared war on my shirt and won via chemical surrender.",
            "A swarm of fireflies unionized into a heart shape and won't disband until I sign a peace treaty.",
            "The love letter I wrote grew wings and is circling the city looking for a better match.",
            "My ride-share driver turned out to be Cupid's intern—detoured to fix 47 other arrows first.",
            "The chocolate fountain I rented achieved escape velocity and is orbiting the chandelier.",
            "My nervous butterflies escaped, formed a flash mob, and blocked the front door with choreography.",
            "The moon filed a restraining order against my rooftop plans—lunar lawyer still in session.",
            "My socks achieved couple status and eloped to the dryer dimension.",
            "A street poet rewrote my apology into a 12-stanza epic—had to memorize it for authenticity.",
            "The wine I chilled turned into a philosopher and won't stop debating existence with the corkscrew.",
            "My playlist achieved free will and switched to breakup anthems mid-shuffle.",
            "A gang of raccoons in tiny tuxedos mugged me for the ring box—still negotiating ransom in shiny coins.",
            "The elevator to romance got stuck between floors 69 and 70 — maintenance says it's symbolic.",
            "I sneezed and accidentally proposed to my reflection—now we're in a committed mirror relationship."
        ],
        "tardiness": [
            "My clock was running on creative time, not real time.",
            "I took the scenic route through a wormhole.",
            "A gang of squirrels held my shoelaces hostage.",
            "I got stuck in a time loop for exactly 23 minutes and just broke free.",
            "My GPS decided to take me on a scenic tour of every construction zone in the city.",
            "I was helping an elderly person with their smartphone and accidentally became their IT support.",
            "My bones filed for asylum in the mattress and the UN granted refugee status.",
            "The couch grew tentacles and they're unionized—any movement triggers a cuddle strike.",
            "I blinked and my eyelids seceded from the United States of Me.",
            "A single dust bunny achieved sentience and is now my life coach demanding 'zero steps today'.",
            "My muscles voted to dissolve parliament and install a nap dictatorship.",
            "The ceiling fan started a cult and I'm the high priest of horizontal worship.",
            "I exhaled so hard my soul left for a beach vacation and forgot the return ticket.",
            "The blanket achieved black hole density—escape velocity exceeds human willpower.",
            "My heartbeat switched to airplane mode and won't reconnect until 2026.",
            "A rogue pillow declared martial law and annexed the entire left side of my body.",
            "The floor lava is real today and I'm the last survivor on Couch Island.",
            "My shadow quit, left a Post-it that says 'find me in the Bahamas'.",
            "I tried to sit up but gravity filed a class-action lawsuit for emotional damages.",
            "The remote is 3 feet away and that's a quest for a level 99 hero, not me.",
            "My blood cells unionized and are picketing for 'no vertical circulation' rights.",
            "A houseplant photosynthesized my motivation and turned it into oxygen I can't use.",
            "The clock melted like Dali and time is now a puddle I refuse to mop.",
            "My neurons formed a conga line to the fridge but got lost at the throw blanket.",
            "I owe my future self a solid and tonight I'm paying in compound interest of immobility.",
            "The Wi-Fi signal built a moat around the bed and stocked it with alligator memes."
        ],
        "homework": [
            "My dog didn't just eat my homework, he peer-reviewed it and said it needed a rewrite.",
            "I accidentally submitted it to a black hole.",
            "The knowledge was too powerful and my paper combusted.",
            "My laptop became convinced it was a gaming console and refused to open educational software.",
            "I was researching so intensely that I accidentally solved a problem that wasn't even assigned yet.",
            "My study playlist achieved sentience and demanded creative control over my academic career.",
            "My pencil achieved enlightenment and ascended to the eraser dimension—left no trace.",
            "The homework portal glitched and redirected me to a 1998 GeoCities fan page for hamsters.",
            "A rogue emoji unionized and replaced every answer with 🦖—grading impossible.",
            "My backpack grew teeth and ate the assignment, then burped up a participation trophy.",
            "The dog didn’t eat it; the dog *became* it via quantum transmogrification—still barking theorems.",
            "I submitted it telepathically but the teacher’s tinfoil hat blocked the signal.",
            "My calculator unionized with the stapler and staged a coup in the junk drawer.",
            "The assignment file achieved escape velocity and is orbiting as space junk labeled 'final.doc'.",
            "A squirrel in a graduation cap mugged me for the flash drive—now tenured at Acorn University.",
            "I wrote it in glitter pen; the glitter staged a coup and declared itself the answer key.",
            "The internet lagged so hard it folded into a paper crane and flew out the window.",
            "My notes spontaneously combusted into a tiny phoenix that only speaks in riddles.",
            "The teacher’s email bounced back with 'recipient ascended to higher plane—try prayer'.",
            "I finished it in my sleep but the dream grader gave me an A in interpretive dance instead.",
            "A pop-up ad promised 'instant homework'—delivered a 3-hour ASMR unboxing of pencils.",
            "My eraser erased the pencil, then the paper, then the concept of deadlines.",
            "The library book grew legs and checked itself out to a parallel universe.",
            "I divided by zero and the math police confiscated my entire backpack for evidence.",
            "The cloud saved it as 'homework_final_final_really.doc' then achieved singularity and left Earth.",
            "I handed it in but the wind read it, laughed, and filed it under 'performance art'."
        ],
    },
}
