# Preset (non-AI) excuses organized by believability level and category.
# believability levels:
# 0 - Plausible professional
# 1 - Barely believable but bold
# 2 - Comedic chaos

PRESET_EXCUSES = {
    0: {  # Plausible professional
        "general": [
            "I had an unexpected commitment I needed to handle and couldn't step away in time.",
            "I ran into an urgent personal matter and needed to take care of it immediately.",
            "A scheduling conflict came up last minute and I had to prioritize it.",
            "I wasn't feeling well and didn't want to make it worse.",
            "There was a bit of a mix-up on my end.",
            "My car broke down on the way, and I'm waiting for roadside assistance. It's going to take a while to sort out.",
            "I'm locked out and the super won't be here for hours. I can't leave until it's resolved.",
            "A pipe just burst in my kitchen, I have to immediately shut off the water and deal with the mess.",
            "I had a family emergency that required my immediate attention.",
            "I was dealing with a work crisis that couldn't wait.",
            "I had to handle an important appointment that couldn't be rescheduled.",
        ],
        "work": [
            "I had to resolve an urgent issue that required my immediate attention.",
            "A last-minute schedule change came up; I'll make up the time.",
            "I was delayed by an unexpected appointment—thanks for understanding.",
            "I had to attend to a critical client matter that just came up.",
            "A system outage required my immediate troubleshooting.",
            "I had to step in for a colleague who called in sick.",
        ],
        "social": [
            "I wasn't feeling well and thought it was best to sit this one out.",
            "Something came up with family and I had to be there.",
            "I overcommitted today and couldn't make it in time—my apologies.",
            "I had a prior commitment I completely forgot about.",
            "I got held up with something urgent at home.",
            "I had to help a friend with an unexpected situation.",
        ],
        "romantic": [
            "I had a personal matter come up unexpectedly—could we reschedule?",
            "I don't want to rush this; can we pick another time when I can be fully present?",
            "Today got complicated; I want to give this the attention it deserves—can we shift it?",
            "I need to take care of something important, but I'd love to reschedule soon.",
            "Something came up that I need to handle—can we do this another time?",
            "I want to be fully focused on you; can we plan for when I'm not so busy?",
        ],
        "tardiness": [
            "I hit an unexpected delay on the way—thanks for your patience.",
            "Traffic and timing didn't cooperate today; I appreciate your understanding.",
            "I miscalculated my timing—won't happen again.",
            "I got stuck behind an accident on my route.",
            "I had to make an unplanned stop that set me back.",
            "I underestimated how long it would take to get here.",
        ],
        "homework": [
            "I underestimated the time required and need an extension to submit my best work.",
            "I ran into technical issues and need a short extension to finalize.",
            "I prioritized accuracy over speed and need a bit more time to complete it properly.",
            "I want to make sure I do this right; can I have a bit more time?",
            "I ran into some complications but I'm almost done.",
            "I'm putting the finishing touches on it and will have it ready soon.",
        ],
    },
    1: {  # Barely believable but bold
        "general": [
            "I was recruited to mediate a neighbor dispute that somehow involved a drone and a raccoon.",
            "I accidentally joined a local committee and they wouldn't let me leave until I voted.",
            "My door got stuck and the only available help was on their lunch break.",
            "I got caught in a spontaneous street performance and couldn't leave without being rude.",
            "My neighbor's WiFi router exploded and I had to help them troubleshoot.",
            "I was mistaken for someone famous and had to play along for 20 minutes.",
        ],
        "work": [
            "My laptop insisted on a 45-minute update right when I sat down to work.",
            "I was locked out of a building with my notes waving at me through the window.",
            "My headset paired with a stranger's device and I had to negotiate a truce.",
            "My email got hacked and I had to spend time securing my account.",
            "The office printer decided to print everything in reverse and I had to fix it.",
            "I got stuck in an elevator for 15 minutes with the CEO.",
        ],
        "social": [
            "I promised to help a friend assemble furniture and we discovered it had existential questions.",
            "I got pulled into a group photo shoot I couldn't escape from.",
            "A delivery driver asked me to sign for 14 packages and we had to inventory them together.",
            "I accidentally became the mediator in a heated debate about pizza toppings.",
            "A stranger asked me for directions and I ended up giving them a full tour.",
            "I got roped into helping someone move a couch up three flights of stairs.",
        ],
        "romantic": [
            "I'm wrangling a home disaster involving a smoke alarm that thinks it's a DJ.",
            "I got stuck helping neighbors find a cat that was loudly supervising us from the roof.",
            "I'm negotiating with my phone which decided emergency mode is its new personality.",
            "My roommate's date showed up early and I had to entertain them.",
            "I accidentally locked myself out and had to wait for a locksmith.",
            "My water heater decided today was the day to break down.",
        ],
        "tardiness": [
            "My map app rerouted me into a scenic detour through every speed bump in the city.",
            "A parade materialized out of nowhere and I was unintentionally part of it.",
            "My coffee staged a rebellion the moment I headed out the door.",
            "I got stuck behind a funeral procession that took the scenic route.",
            "A street fair blocked my usual route and I had to navigate around it.",
            "My car decided to make a weird noise and I had to pull over to investigate.",
        ],
        "homework": [
            "My notes synced into another dimension; I'm retrieving them one bullet point at a time.",
            "I discovered my citations had children and each one needed attention.",
            "A spreadsheet unionized and demanded better formatting before proceeding.",
            "My research rabbit hole led me to discover something way more interesting.",
            "My outline decided to reorganize itself alphabetically by mood.",
            "I got distracted by a Wikipedia spiral and lost three hours.",
        ],
    },
    2: {  # Comedic chaos
        "general": [
            "A wizard stole my car keys.",
            "I was busy converting oxygen to carbon dioxide.",
            "My pet rock needed emergency emotional support.",
            "I was abducted by aliens but they returned me early.",
            "I discovered I can speak to pigeons and we had important business.",
            "My shadow filed for independence and I had to negotiate.",
        ],
        "work": [
            "My computer screen froze, and I got frostbite on my eyeballs.",
            "I was stuck in a time loop for the first half of the day.",
            "The corporate synergy levels were too low for me to be productive.",
            "My desk chair achieved sentience and demanded a raise.",
            "I was trapped in a meeting that violated the Geneva Convention.",
            "My coffee mug unionized and refused to hold coffee.",
        ],
        "social": [
            "I had to attend the annual meeting of the International Society of Procrastinators.",
            "My social battery was at 1% and the charger is missing.",
            "I was told there would be snacks, and I'm philosophically opposed to snack-less events.",
            "I'm currently in a standoff with my houseplant over who gets to use the good lighting today.",
            "My social anxiety filed a restraining order against me leaving the house.",
            "I was busy negotiating peace between my two houseplants.",
        ],
        "romantic": [
            "I was busy practicing your name in the mirror.",
            "My astrologer advised against making any good decisions today.",
            "Cupid's arrow is stuck in traffic.",
            "I'm in the middle of a very important relationship with my Netflix algorithm.",
            "My cat is giving me relationship advice and we're not done with our consultation yet.",
            "Mercury is in retrograde and my phone autocorrected all my messages to emojis.",
        ],
        "tardiness": [
            "My clock was running on creative time, not real time.",
            "I took the scenic route through a wormhole.",
            "A gang of squirrels held my shoelaces hostage.",
            "I got stuck in a time loop for exactly 23 minutes and just broke free.",
            "My GPS decided to take me on a scenic tour of every construction zone in the city.",
            "I was helping an elderly person with their smartphone and accidentally became their IT support.",
        ],
        "homework": [
            "My dog didn't just eat my homework, he peer-reviewed it and said it needed a rewrite.",
            "I accidentally submitted it to a black hole.",
            "The knowledge was too powerful and my paper combusted.",
            "My laptop became convinced it was a gaming console and refused to open educational software.",
            "I was researching so intensely that I accidentally solved a problem that wasn't even assigned yet.",
            "My study playlist achieved sentience and demanded creative control over my academic career.",
        ],
    },
}
